[phases.setup]
nixPkgs = ["nodejs_20", "yarn"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "rm -f package-lock.json",
  "yarn install --network-timeout 300000"
]

[phases.build]
dependsOn = ["install"]
cmds = ["yarn build"]

[start]
cmd = "yarn start"

[variables]
NODE_VERSION = "20"